[global]
# Configurações globais do Streamlit

[theme]
# Tema claro corporativo
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Configurações do servidor
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
# Configurações do navegador
gatherUsageStats = false
serverAddress = "localhost"

[client]
# Configurações do cliente
showErrorDetails = true
toolbarMode = "minimal"

[logger]
# Configurações de log
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[runner]
# Configurações de execução
magicEnabled = true
installTracer = false
fixMatplotlib = true

[deprecation]
# Configurações de deprecação
showPyplotGlobalUse = false

