name: Update Database - Madrugada

on:
  schedule:
    # Executar às 01:15 da manhã (horário ótimo - 4:15 BRT)
    - cron: '15 1 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Razão para executar a atualização'
        required: false
        default: 'Atualização manual'
        type: string

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb==1.2.2
          pip install -r requirements.txt

      - name: Set file permissions
        run: chmod +x scripts/*.py

      - name: Update database
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          CVCRM_EMAIL: ${{ secrets.CVCRM_EMAIL }}
          CVCRM_TOKEN: ${{ secrets.CVCRM_TOKEN }}
          CV_VENDAS_BASE_URL: ${{ secrets.CV_VENDAS_BASE_URL }}
          SIENGE_BASE_URL: ${{ secrets.SIENGE_BASE_URL }}
          SIENGE_TOKEN: ${{ secrets.SIENGE_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}/scripts:${{ github.workspace }}
        run: |
          echo "🌙 Iniciando atualização do MotherDuck (madrugada)..."
          python -u scripts/update_motherduck_vendas.py
      
      - name: Notify success
        if: success()
        run: echo "✅ Database updated successfully at $(date)"
      
      - name: Notify failure
        if: failure()
        run: echo "❌ Database update failed at $(date)"
